// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaXSHSdtOKupjwIQ2omUuDcS1Zr8BiRwo',
    appId: '1:897138972448:web:4f28a3957a72968f046945',
    messagingSenderId: '897138972448',
    projectId: 'vigilerp',
    authDomain: 'vigilerp.firebaseapp.com',
    storageBucket: 'vigilerp.appspot.com',
    measurementId: 'G-R3VXB2306D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuSoCErZyIhhyMlwGOdH9uZO-nR8Jbb8',
    appId: '1:897138972448:android:826651682b39f593046945',
    messagingSenderId: '897138972448',
    projectId: 'vigilerp',
    storageBucket: 'vigilerp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9bK_cBVq0Czkp_tpWPId2rsPq-2P1Lc',
    appId: '1:897138972448:ios:0698fe51cb046837046945',
    messagingSenderId: '897138972448',
    projectId: 'vigilerp',
    storageBucket: 'vigilerp.appspot.com',
    iosBundleId: 'com.vigil.vigilErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9bK_cBVq0Czkp_tpWPId2rsPq-2P1Lc',
    appId: '1:897138972448:ios:0698fe51cb046837046945',
    messagingSenderId: '897138972448',
    projectId: 'vigilerp',
    storageBucket: 'vigilerp.appspot.com',
    iosBundleId: 'com.vigil.vigilErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaXSHSdtOKupjwIQ2omUuDcS1Zr8BiRwo',
    appId: '1:897138972448:web:c6b6ee3464f41565046945',
    messagingSenderId: '897138972448',
    projectId: 'vigilerp',
    authDomain: 'vigilerp.firebaseapp.com',
    storageBucket: 'vigilerp.appspot.com',
    measurementId: 'G-DM38G3GW4Z',
  );
}
